[lemmy]
instanceURL = "https://jlai.lu"

[lemmy.account]
userOrEmail = "user@mail.com"
password = "tHeP@sSwOrD"

# Returns Tournesol links for YouTube URLs
#
# Example: https://www.youtube.com/watch?v=2vPhySbRETM => https://tournesol.app/entities/yt:2vPhySbRETM
[[url]]
youtube = 'https?://(?:(?:www|m)\.)?youtu(?:\.be/|be\.com/(?:watch\?v=|shorts/))([\w\d-]{11})[&?]?([\w\d?&=%/-]*)'
tournesol = 'https://tournesol.app/entities/yt:{{ vid }}'
tournesolapi = 'https://api.tournesol.app/polls/videos/entities/yt:{{ vid }}'

[[reply]]
msg = '''
{{if len .Matches | eq 1}}This video{{else}}These videos{{end}} has been compared on Tournesol:

{{range $i, $match := .Matches}}
- [{{ Video name }}]({{ tournesol url }}) ({{ Tournesol evaluation }})
{{end}}
'''
